version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=4zi
      - MYSQL_USER=4zi
      - MYSQL_PASSWORD=4zi
    ports:
      - "3306:3306"
    volumes:
      - ./4zi.sql:/docker-entrypoint-initdb.d/4zi.sql
  sen-tree-pay:
    build:
      context: .
    depends_on:
      - mysql
    image: tomy0000000/sen-tree-pay:1.0
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    volumes:
      - application:/usr/share/nginx/sen-tree-pay
  nginx:
    depends_on:
      - sen-tree-pay
    image: tomy0000000/nginx:1.17-1.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - application:/usr/share/nginx/sen-tree-pay

volumes:
  application:
